Change: error in awk Add: regional_disk_images_check, regional_disk_images_delete, regional_disks_image_dubles, regional_emm_clear_disks_copies

diff --git a/regional_import b/regional_import
--- a/regional_import
+++ b/regional_import
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 #set -x
-readonly Version="0.0.6"
+readonly Version="0.0.8"
 # 
 #
 
@@ -49,14 +49,15 @@ function check_dir() {
 }
 
 function curr_time() {
-  echo "at $(date +%Y-%m-%d_%H:%M:%S)"
+#  echo "at $(date +%Y-%m-%d_%H:%M:%S)"
+  echo "at $(date +%Y.%m.%d_%H:%M:%S)"
 }
 
 function set_ImagesFile() {
 # $ImagesDir $ImagesFile
 
-#	ls $1/*.img | awk -F_ '{if ($4=="F1") print $1"_"$2}' | awk -F/ '{print $NF}' > $2
-	ls $1/*.img | awk -F_ '{if ($4=="F1") print $1"_"$2,$3}'  > $2
+#	ls $1/*.img | awk -F_ '{if ($4=="F1" || $4~/^F1\./) print $1"_"$2}' | awk -F/ '{print $NF}' > $2
+	ls $1/*.img | awk -F_ '{if ($4=="F1" || $4~/^F1\./) print $1"_"$2,$3}'  > $2
 }
 
 function do_import1() {
@@ -68,14 +69,14 @@ function do_import1() {
 	echo "PID:$!"
   wait $PID
 	RC=$?
-	echo "Finish Import 1 of Dir $1, RC=$RC $(curr_time)"
+	echo "Finish Import 1 of the Dir $1, RC=$RC $(curr_time)"
 }
 
 function do_import2() {
 # $Image
 
   local DT="-s 01/01/2001 00:00:00 -e 01/01/2030 00:00:00"
-	echo "Start import of image $1 $(curr_time)"
+	echo "Start import of the image $1 $(curr_time)"
 #  return
 	
   nohup $CMDimport -backupid $1 -L $DirLog/$(basename $0)_import2_${1}.log -l $DT &
@@ -83,7 +84,7 @@ function do_import2() {
 	echo "PID:$!"
   wait $PID
 	RC=$?
-	echo "Finish import of image $1, RC=$RC $(curr_time)"
+	echo "Finish import of the image $1, RC=$RC $(curr_time)"
 	return $RC
 }
 
@@ -94,7 +95,7 @@ function do_dupl() {
 	get_dupl_params
 	local DT=""
 	local Own=""
-	echo "Start duplication of image $1 $(curr_time)"
+	echo "Start duplication of the image $1 $(curr_time)"
 #  return
 	
   nohup $CmdDupl $DT -backupid $1 -cn $2 -dp $DVP -dstunit $DSTU -rl $Retn -set_primary 1 -fail_on_error 0 $Own -L $DirLog/$(basename $0)_dupl_${1}.log -v & 
@@ -102,7 +103,7 @@ function do_dupl() {
   echo "PID:$!"
   wait $PID
 	RC=$?
-	echo "Finish duplication of image $1, RC=$RC $(curr_time)"
+	echo "Finish duplication of the image $1, RC=$RC $(curr_time)"
 	return $RC
 }
 
@@ -114,7 +115,7 @@ function delete_disk_copy() {
 	get_image_status $Image
 	local ImageStatus=$?
 	if [[ $ImageStatus -ne cAfterDupl ]]; then
-	  echo "Err Invalid status $ImageStatus of image $Image"
+	  echo "Err Invalid status $ImageStatus of the image $Image"
 	  return 1
 	fi
 	
@@ -126,7 +127,7 @@ function delete_disk_copy() {
 	PID=$!
   wait $PID
 	RC=$?
-	echo "Finish Exclude disk copy $Copy, $1, RC=$RC $(curr_time)"	
+	echo "Finish Exclude the disk copy $Copy, $1, RC=$RC $(curr_time)"	
 	return $RC
 }
 
@@ -215,31 +216,32 @@ function one_dir_import() {
 		case $ImageStatus in
 			0)
 				do_import1 $ImagesDir
-				ImageStatus=$(get_image_status $Image)
+				get_image_status $Image
+		    ImageStatus=$?
 				if [[ $ImageStatus -eq 0 ]]; then
-					echo "$Err Image $Image don't pre-imported !"
+					echo "$Err The Image $Image don't pre-imported !"
 					continue
 	#		    exit 1
 				fi
 				;&
 			1)
 				do_import2 $Image
-				[[ $RC -gt 0 ]] && continue
+				[[ $RC -gt 0 ]] && [[ $RC -ne 191 ]] && continue
 				;&
 			2)
 				do_dupl $Image $Copy
-	#			echo "Image $Image is duplicated."
+	#			echo "The Image $Image is duplicated."
 				[[ $RC -gt 0 ]] && continue
 				;&
 			3)
 				delete_disk_copy $Image $Copy
-	#			echo "Image $Image - copy on disk is excluded."
+	#			echo "The Image $Image - copy on disk is excluded."
 				;;
 			4)
-				echo "Image $Image - copy on disk had been excluded."
+				echo "The Image $Image - copy on disk had been excluded."
 				;;
 			*)
-			echo "$Err Invalid ImageStatus:$ImageStatus for $Image !"
+			echo "$Err Invalid ImageStatus:$ImageStatus for the $Image !"
 		esac
 	done < $ImagesFile
 
@@ -266,7 +268,7 @@ do
 
 	SubDirFile="${Dir}_$(basename $0)_subdirs.txt"
 
-	find $Dir0 -name "*.img" -print | awk -F_ '{if ($4=="F1") print $1"_"$2}' | xargs dirname | sort -u > $SubDirFile
+	find $Dir0 -name "*.img" -print | awk -F_ '{if ($4=="F1" || $4~/^F1\./) print $1"_"$2}' | xargs dirname | sort -u > $SubDirFile
 
 	while read SubDir
 	do
